version: '2'

services:
  nginx:
    image: arkasha/ubuntu-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./sites:/etc/nginx/sites-enabled
    links:  
      - mysql:mysql
      - phpfpm:phpfpm
      
  phpfpm:
    image: arkasha/ubuntu-phpfpm:latest
    volumes:
      - ../:/var/www
    links:  
      - mysql:mysql

  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ../:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

